import type { ReactNode } from 'react';
import { Bird, ArrowLeft } from 'lucide-react';

export function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="sticky top-0 z-10 border-b bg-background/80 backdrop-blur">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-6 py-4">
          <div className="flex items-center gap-2">
            <Bird className="size-4 text-primary" />
            <span className="font-semibold tracking-tight">Lyrebird</span>
          </div>
          <a
            href="/"
            className="flex items-center gap-1.5 text-sm text-muted-foreground transition-colors hover:text-foreground"
          >
            <ArrowLeft className="size-3.5" />
            Back to sign in
          </a>
        </div>
      </header>

      {/* Content */}
      <main className="mx-auto max-w-3xl px-6 py-12">
        <div className="mb-10">
          <h1 className="text-3xl font-bold tracking-tight">
            Terms of Service
          </h1>
          <p className="mt-2 text-sm text-muted-foreground">
            Last updated: February 21, 2026
          </p>
        </div>

        <div className="prose prose-zinc dark:prose-invert max-w-none space-y-8 text-[0.9375rem] leading-relaxed text-foreground">
          <section>
            <p className="text-muted-foreground">
              By accessing or using Lyrebird, you agree to be bound by these
              Terms of Service. If you do not agree, do not use the service.
            </p>
          </section>

          <Section title="1. Description of Service">
            <p>
              Lyrebird is a real-time sentiment analysis dashboard for the
              Bluesky social network. It ingests public posts from Bluesky,
              processes them through a sentiment analysis engine, and presents
              aggregated insights through an interactive interface.
            </p>
            <p>
              The service is provided for informational and analytical purposes
              only. Lyrebird does not publish, store, or redistribute the
              content of individual Bluesky posts beyond what is necessary for
              analysis.
            </p>
          </Section>

          <Section title="2. Account Registration">
            <p>
              Access to Lyrebird requires authentication via Google OAuth. By
              signing in, you authorize Lyrebird to receive your Google
              account&apos;s basic profile information (name, email address, and
              profile picture) solely for authentication purposes.
            </p>
            <p>
              You are responsible for maintaining the security of your Google
              account. Lyrebird will not be liable for any loss arising from
              unauthorized access resulting from your failure to secure your
              credentials.
            </p>
          </Section>

          <Section title="3. Acceptable Use">
            <p>You agree not to:</p>
            <ul className="ml-4 list-disc space-y-1.5 text-muted-foreground">
              <li>
                Use the service for any unlawful purpose or in violation of any
                applicable laws
              </li>
              <li>
                Attempt to reverse engineer, scrape, or extract raw data from
                the service
              </li>
              <li>
                Use automated scripts or bots to access the dashboard in ways
                that would disproportionately burden the infrastructure
              </li>
              <li>
                Misrepresent the source or nature of the data or insights
                provided by Lyrebird
              </li>
              <li>
                Interfere with or disrupt the service or its connected
                infrastructure
              </li>
            </ul>
          </Section>

          <Section title="4. Data Sources and Accuracy">
            <p>
              Lyrebird sources data from the Bluesky public firehose and AT
              Protocol. Analysis results are generated by machine learning
              models and are inherently probabilistic. They should not be
              treated as definitive, legally binding, or fully accurate
              representations of public sentiment.
            </p>
            <p>
              We make no warranties, express or implied, regarding the accuracy,
              completeness, or fitness of the data for any particular purpose.
            </p>
          </Section>

          <Section title="5. Intellectual Property">
            <p>
              The Lyrebird software, interface, and underlying models are the
              intellectual property of their respective creators. No part of the
              service may be reproduced, distributed, or transmitted in any form
              without prior written consent.
            </p>
            <p>
              Content sourced from Bluesky remains the property of its original
              authors under the terms of the AT Protocol and Bluesky&apos;s own
              policies.
            </p>
          </Section>

          <Section title="6. Limitation of Liability">
            <p>
              To the maximum extent permitted by applicable law, Lyrebird and
              its operators shall not be liable for any indirect, incidental,
              special, consequential, or punitive damages arising from your use
              of, or inability to use, the service.
            </p>
            <p>
              The service is provided &quot;as is&quot; and &quot;as
              available&quot; without any warranties of any kind.
            </p>
          </Section>

          <Section title="7. Modifications">
            <p>
              We reserve the right to modify these terms at any time. Continued
              use of the service after changes have been posted constitutes your
              acceptance of the revised terms. We will update the date at the
              top of this page when changes are made.
            </p>
          </Section>

          <Section title="8. Governing Law">
            <p>
              These terms are governed by and construed in accordance with
              applicable law. Any disputes arising from these terms or your use
              of Lyrebird shall be resolved through good-faith negotiation.
            </p>
          </Section>

          <Section title="9. Contact">
            <p>
              Questions about these Terms of Service can be directed to the
              project maintainers via the repository or contact information
              listed in the project documentation.
            </p>
          </Section>
        </div>
      </main>

      <footer className="border-t py-8">
        <p className="text-center text-xs text-muted-foreground">
          &copy; {new Date().getFullYear()} Lyrebird &mdash;{' '}
          <a
            href="/privacy"
            className="underline underline-offset-4 hover:text-foreground transition-colors"
          >
            Privacy Policy
          </a>
        </p>
      </footer>
    </div>
  );
}

function Section({ title, children }: { title: string; children: ReactNode }) {
  return (
    <section className="space-y-3">
      <h2 className="text-base font-semibold tracking-tight">{title}</h2>
      <div className="space-y-3 text-muted-foreground">{children}</div>
    </section>
  );
}
