import {
  pgTable,
  uuid,
  text,
  timestamp,
  jsonb,
  index,
} from 'drizzle-orm/pg-core';
import { JobStatus } from '@app/shared-types';
import { user } from './auth.schema';

/**
 * Jobs table - tracks all sentiment analysis jobs
 *
 * This table stores metadata about user requests:
 * - User prompt (e.g., "Egypt")
 * - Search strategy generated by AI
 * - Job status (pending, in_progress, completed, failed)
 */
export const jobs = pgTable(
  'jobs',
  {
    id: uuid('id').defaultRandom().primaryKey(),

    userId: text('user_id').references(() => user.id, { onDelete: 'cascade' }),

    prompt: text('prompt').notNull(),

    // AI-generated search strategy (stored as JSON)
    searchStrategy: jsonb('search_strategy'),

    status: text('status', {
      enum: ['pending', 'in_progress', 'completed', 'failed'],
    })
      .notNull()
      .default('pending')
      .$type<JobStatus>(),

    errorMessage: text('error_message'),

    // Timestamps
    createdAt: timestamp('created_at').notNull().defaultNow(),
    updatedAt: timestamp('updated_at').notNull().defaultNow(),
    completedAt: timestamp('completed_at'),
  },
  (table) => [
    index('idx_jobs_user_id_created_at').on(table.userId, table.createdAt),
  ],
);

// Type inference for TypeScript
export type Job = typeof jobs.$inferSelect;
export type NewJob = typeof jobs.$inferInsert;
